docs.iml
docs/deployment/authentication.md

associated issue in opencti-platform: https://github.com/OpenCTI-Platform/opencti/issues/2419

[docs] automatically create groups on SSO (#4)

---

docs/deployment/authentication.md

was required, missed it in last PR #24

added scope to env. config for auth0 example

---

docs/development/environment.md
docs/development/environment_windows.md
mkdocs.yml

Intended to meet the need of the following Issue submission: https://github.com/OpenCTI-Platform/docs/issues/27

[docs] Windows 10 Bare Metal setup instructions for Developers

---

docs/usage/notifications.md

instance trigger documentation

[docs] instance triggers

---

docs/deployment/authentication.md

issue: https://github.com/OpenCTI-Platform/docs/issues/46

[docs] SAML Organization mapping mistake fix (#46)

---

docs/deployment/authentication.md

This PR should overwrite the 5.9 documentation (don't wait for the release) !!!

[docs] SSO organization mapping fix

---

docs/deployment/rollover.md

Added section about bootstrapping new indices (with aliases), if not the re-index will fail :)

[docs] Update rollover.md - add bootstrapping indices section

---

docs/administration/entities.md

Doc Issue : https://github.com/OpenCTI-Platform/docs/issues/51
OpenCTI Issue : https://github.com/OpenCTI-Platform/opencti/issues/3544

[docs] Update hidden types documentation

---

docs/usage/deduplication.md

Added documentation on expected behavior for alias names.

[docs] Names and aliases management

---

docs/deployment/installation.md

* Update link maintained Helm Chart for Kubernetes [opencti/issues/3573](https://github.com/OpenCTI-Platform/opencti/issues/3573)
* Typo trim whitespaces

[deployment] Update Helm Charts reference

---

docs/administration/users.md

[issue/120](https://github.com/OpenCTI-Platform/docs/issues/120)
update data sharing capabilities

[docs] Update data sharing capabilities (#120)

---

docs/administration/users.md

update users to introduce max confidence level for mutli group

Update doc 

---

docs/deployment/configuration.md

More Details about this PR in Following Issue: https://github.com/OpenCTI-Platform/docs/issues/136
---
:white_check_mark:  __Results:__

[bucket-s3] Enhance Bucket S3 Configuration with Parameter Value Examples

---

docs/development/connectors.md

Editing of connectors.md

---

docs/deployment/configuration.md
docs/deployment/managers.md
docs/deployment/overview.md
docs/reference/data-telemetry.md
mkdocs.yml

To be merged along with the telmetry PRs.
- https://github.com/OpenCTI-Platform/opencti/pull/6634
-

Adding description of data collected by telemetry (opencti:issue/6292)

---

docs/reference/filters.md

issue: https://github.com/OpenCTI-Platform/docs/issues/164

[docs] representative filter (#164)

---

docs/administration/policies.md
docs/administration/segregation.md
docs/administration/users.md
docs/usage/dashboards-share.md
docs/usage/export.md

issue: https://github.com/OpenCTI-Platform/docs/issues
Github PR: https://github.com/OpenCTI-Platform/opencti/pull/7107

[docs] max shareable markings defined at the group level (#174)

---

docs/administration/users.md

update capabilites table :
- Dashboard & investigations
- Data sharing & ingestions
- Administration

[doc] update capabilities (#5550)

---

docs/deployment/breaking-changes.md
mkdocs.yml

This PR bootstraps a new section dedicated to breaking changes to our API, and pointers to migration guides.

[deployment] add section on deprecation/migration

---

docs/deployment/breaking-changes.md

[deployment] clarify breaking-changes (#186)

---

docs/deployment/configuration.md

Along with https://github.com/OpenCTI-Platform/opencti/pull/7783

Add usage of configuration for iframe (#7756)

---

docs/administration/users.md

Add 1 line for the new capability 'Bypass mandatory fields'
Wait for PR : [#7665](https://github.com/OpenCTI-Platform/opencti/pull/7665)

[docs] add new capability Bypass mandatory fields (#3304)

---

docs/deployment/configuration.md
docs/usage/delete-restore.md

New config for the trash + improve usage doc
To merge when  https://github.com/OpenCTI-Platform/opencti/pull/8964 is merged

[usage/deployment] update documentation for trash system (#221)

---

docs/reference/filters.md

- update documentation about filters 
https://github.com/OpenCTI-Platform/docs/issues/226

[docs] update filters documentation (#226)

---

docs/assets/css/custom.css

[docs] Changing the custom css to have a wider doc

---

docs/usage/import-automated.md

import-automated fix

---

docs/usage/exploring-analysis.md
docs/usage/exploring-cases.md

closes: https://github.com/OpenCTI-Platform/docs/issues/247

[docs] add authorized members doc for cases and groupings

---

docs/deployment/configuration.md

To be merged after https://github.com/OpenCTI-Platform/opencti/pull/9244 is merged.

Update ingestion manager with new options for RSS and CSV

---

docs/administration/notifiers.md
docs/deployment/breaking-changes.md
docs/deployment/configuration.md

Documentation for https://github.com/OpenCTI-Platform/opencti/pull/9810

Add documentation on webhook options

---

docs/reference/filters.md

following https://github.com/OpenCTI-Platform/opencti/issues/9144

[reference] add new compatible filters key

---

docs/reference/filters.md

Add 'within' filter operator explanations + examples
Docs issue : https://github.com/OpenCTI-Platform/docs/issues/255
Opencti PR : https://github.com/OpenCTI-Platform/opencti/pull/10024

[docs] Relative datetime filter operator (within) (#255)

---

docs/deployment/configuration.md

Documents the added override configuration option from https://github.com/OpenCTI-Platform/opencti/pull/9995

Add `openbas_api_url` to deployment configuration docs

---

docs/reference/filters.md

update 'in regards of' filter doc warning after the reindexation of target relationships
linked to OpenCTI PR : https://github.com/OpenCTI-Platform/opencti/pull/10329

[docs] update regardingOf filter doc after targets relationships reindex

---

docs/deployment/installation.md

Removed warnings/recommendation about adding settings that are already present.

Update installation.md: remove warnings on elasticsearch and rabbitmq conf

---

docs/administration/retentions.md
docs/deployment/authentication.md
docs/deployment/rollover.md

Fix following the issues:
- https://github.com/OpenCTI-Platform/docs/issues/290
- https://github.com/OpenCTI-Platform/docs/issues/289
- https://github.com/OpenCTI-Platform/docs/issues/288

Add SAML Audience Parameter, OpenSearch Docs, and Retention Policies Format

---

docs/usage/import/csv-feed.md

This is the OneClick deploy documentation. NEed first the @Kroustille documentation about enrollment to get the link to insert (instead of the XXX letters)

[CSV Feed] - OneClick deploy

---

.github/worklows/auto-set-labels.yml
.github/worklows/check-verified-commit.yml

Added commit signature verification.
Added automation of the Filigran Teams label.

[docs] Add auto-set-labels and check-verified-commit
